# Generated by Django 4.0.5 on 2022-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_p', '0005_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='category',
            field=models.ManyToManyField(to='news_p.category'),
        ),
    ]
