# Generated by Django 4.0.5 on 2022-06-20 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_p', '0006_remove_category_subscribers_subscribers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
