# Generated by Django 4.0.5 on 2022-07-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_p', '0010_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dataCreation',
            new_name='dateCreation',
        ),
    ]
